substitutions:
  name: salt-level
  friendly_name: "Salt Level"
  board: d1_mini

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: ${board}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name} Fallback AP
    password: !secret salt_level_ap_password

captive_portal:
  
logger:

api:
  encryption:
    key: !secret salt_level_api_encryption_key

ota:
  - platform: esphome
    password: !secret salt_level_ota_password

text_sensor:
  - platform: version
    name: ESPHome Version - ${friendly_name}

  - platform: wifi_info
    ip_address: 
      name: IP - ${friendly_name}

interval:
  - interval: 20s
    then:
      - component.update: vl53l0x_sensor

i2c:
  sda: D2
  scl: D1
  scan: true

sensor:
  - platform: vl53l0x
    id: vl53l0x_sensor
    name: Reading
    update_interval: never
    unit_of_measurement: "%"
    accuracy_decimals: 0
    filters:
      - lambda: |-
          ESP_LOGD("custom", "Value measured. x= %f", x);
          const int BARREL_HEIGHT = 100;
          const int GAP = 15;          
          if(isnan(x) || x > BARREL_HEIGHT + GAP) { return 0; }
          else {
          return ((BARREL_HEIGHT - x *100)/(BARREL_HEIGHT - GAP))*100;
          }
    on_value:
      then:
        - light.turn_on:
            id: status_led
            red: 0.0
            green: 1.0
            blue: 0.0
        - delay: 1500ms
        - light.turn_off: status_led
        - delay: 1500ms
        - light.turn_on:
            id: status_led
            red: 1.0
            green: 0.0
            blue: 0.0

binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    id: manual_measure_button
    internal: true
    on_press:
      then:
        - component.update: vl53l0x_sensor
        - logger.log: Button pressed

button:
  - platform: template
    name: Trigger Salt Measurement
    on_press:
      then:
        - component.update: vl53l0x_sensor

  - platform: restart
    name: Restart ${friendly_name}

output:
  - platform: esp8266_pwm
    pin: D5    
    id: led_red

  - platform: esp8266_pwm
    pin: D7    
    id: led_blue

  - platform: esp8266_pwm
    pin: D6    
    id: led_green

light:
  - platform: rgb
    id: status_led
    red: led_red
    green: led_green
    blue: led_blue